config/routes.rb
Rails.application.routes.draw do
  
  resources :series

  resources :search, param: :query

  get 'welcome/index'
  
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @results = Tmdb::Search.tv(params[:query]).results
  end
end

app/controllers/series_controller.rb
class SeriesController < ApplicationController
  def show
    @series = Tmdb::TV.detail(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @popular_shows = Tmdb::TV.popular.results
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/series_helper.rb
module SeriesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DiscoverTV</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Materialize's Icons -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  </head>

  <body>
    
    <div class="row blue-grey darken-3 valign-wrapper">
      <div class="col s4 offset-s1">
        <a class="teal-text text-lighten-4" href="<%= root_path %>">
          <i class="material-icons left">home</i>
          <span class="">DiscoverTV</span>
        </a>
      </div>

      <%= form_tag("/search", method: "get") do %>
        <div class="col s1.5">      
          <button class="btn waves-effect waves-light valign-wrapper" type="search">Search
            <i class="material-icons right">search</i>
          </button>
        </div>  
        <div class="col s6">
          <input class="teal-text text-lighten-4" placeholder="Search for a show..." id="query" name="query" type="text">
        </div>
      <% end %>
    </div>
    
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/search/index.html.erb
<div class="row">
    <h3><%= Tmdb::Search.tv(params[:query]).total_results %> Search Results for "<%= params[:query] %>"</h3>
    <div class="row"> 
        <% @results.each do |show| %>            
            <%= link_to series_path(show.id) do %>
                <div class="col s4 hoverable shows-grid">                    
                    <% if show.poster_path %>
                        <img class="left" src="https://image.tmdb.org/t/p/w92<%= show.poster_path %>">
                    <% else %>
                        <div class="left">
                            <%= image_tag("no_image_small.png") %>
                        </div>
                    <% end %>
                    <div class="shows-grid-text center-align">
                        <strong><%= show.name %></strong>
                        </br>
                        <small>
                            <% if show.first_air_date.length > 0 %>
                                (<%= show.first_air_date %>)
                                </br>
                            <% end %>
                            Score: <%= show.vote_average %>
                        </small>
                    </div>           
                </div>
            <% end %>
        <% end %>
    </div>
</div>

app/views/series/show.html.erb
<div class="row teal lighten-4 valign-wrapper">
    <div class="col s10">
        <h1><%= @series.name %></h1>
    </div>
    <div class="col s3 pull-s0.5">
        <% if @series.first_air_date.length > 0 %>
            <h6>(<%= @series.first_air_date %>)</h6>
        <% end %>
    </div>
</div>
<div class="row">
    <div class="col s4">
        <% if @series.poster_path %>
            <img class="left" src="https://image.tmdb.org/t/p/w185<%= @series.poster_path %>">
        <% else %>
            <div class="left">
                <%= image_tag("no_image_big.png") %>
            </div>
        <% end %>
    </div>
    <div class="col s8">
        <table class="highlight">
            <tr> 
                <td colspan="2"><%= @series.overview %></td>
            </tr>
            <tr>
                <td>Score: <%= @series.vote_average %></td>
                <td class="blue-grey-text text-darken-3"><a href="<%= @series.homepage %>"><i class="material-icons">link</i>Website</a></td>
            </tr>
        </table>
    </div>
</div>
<div>

</div>

app/views/welcome/index.html.erb
<div class="row">
    <h3>Top 20 Shows</h3>
    <div class="row"> 
        <% @popular_shows.each do |show| %>            
            <%= link_to series_path(show.id) do %>
                <div class="col s4 hoverable shows-grid">                    
                    <% if show.poster_path %>
                        <img class="left" src="https://image.tmdb.org/t/p/w92<%= show.poster_path %>">
                    <% else %>
                        <img class="left" src="">
                    <% end %>
                    <div class="shows-grid-text center-align">
                        <strong><%= show.name %></strong>
                        </br>
                        <small>Score: <%= show.vote_average %></small>
                    </div>           
                </div>
            <% end %>
        <% end %>
    </div>
</div>